# Generated by Django 4.2.6 on 2023-12-28 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_accessrecors'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AccessRecors',
            new_name='AccessRecord',
        ),
    ]
